version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - docker-compose -f $CODEBUILD_SRC_DIR/docker-compose.yml up -d --build
  post_build:
    commands:
      - echo Build completed on `date`